### ISSUE TITLE
[BUG] Careamics fresh install broken, installed Zarr alpha version

### ISSUE THREAD

**Issue by nunopimpaomartins** [CAREamics/careamics#168]
**Describe the bug**
`careamics` installed latest alpha version of `zarr>=3.0.*` which breaks when running example notebooks.

**To Reproduce**
1. Install `careamics` following wiki instructions ([link](https://careamics.github.io/0.1/installation/)).
1. Pypi package was installed as `pip install --pre "careamics[examples, wandb, tensorboard]"`
1. Run example notebook `SEM_Noise2Void.ipynb`
1. error in first cell when importing Zarr: `ImportError: cannot import core from zarr`

**Expected behavior**
To run the example notebook without problems.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version 22.04

**Environment:**
Packages attached as text file.
[careamics_env.txt](https://github.com/user-attachments/files/15958461/careamics_env.txt)

**Additional context**
Downgrading `zarr` to version `2.18.2` makes everything work again.

**Comment by jdeschamps** [comment]
Hi Nuno!

Thanks! Indeed, the latest pre-release still has that problem. It is fixed in `main` since https://github.com/CAREamics/careamics/pull/149 and will be in the next pre-release!

Hopefully, this week! I leave this open until it is released.

**Comment by jdeschamps** [comment]
The new pre-release should have fixed that.
