### ISSUE TITLE
[BUG] WandB logger experiment name is always default with n2v configuration

### ISSUE THREAD

**Issue by nunopimpaomartins** [CAREamics/careamics#190]
**Describe the bug**
While using N2V configuration and the WandB as logger, the experiment name is always shown as "CAREmics" in WandB runs even when the name is set in the configuration.

**To Reproduce**
Code snippet allowing reproducing the behaviour:
```python
config = create_n2v_configuration(
    experiment_name="n2v_zs_npm_ex003_re03_40x_pfaga_dapi",
    data_type="tiff",
    axes="ZYX",
    patch_size=(32, 64, 64),
    batch_size=16,
    num_epochs=100,
    logger="wandb",
)

print(config)

# instantiate a CAREamist
careamist = CAREamist(source=config)

# train
careamist.train(
    train_source=root_path,
    val_percentage=0.1,
    val_minimum_split=1,
)
```

**Expected behavior**
The experiment name in WandB logger should match the defined name in the configuration of the model.

**Screenshots**
Screenshot of WandB logging
![wandb](https://github.com/user-attachments/assets/9b673e02-7d7a-4fb8-b6f6-d0b54e413e79)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version 22.04

**Environment:**
[careamics_env_20240725.txt](https://github.com/user-attachments/files/16380488/careamics_env_20240725.txt)

**Comment by melisande-c** [comment]
Thank you for bringing this to our attention! It seems the `experiment_name` argument that is used to initialise the `CAREamist` class (default is "CAREamics"), is what is being passed on to the logger instead of the experiment name in the config. We can get this fixed quickly!
