### ISSUE TITLE
More model's documentation for the BMZ export

### ISSUE THREAD

**Issue by mese79** [CAREamics/careamics#276]
Just some notes came up during the recent AI4Life meeting:
- The model's `documentation` should state what the model does in a kind of title or heading (I mentioned tags, but they wanted it to be more clear).
- The model's `documentation` should have a **Validation** section. It is optional by default, but "our internally uploaded models should be exemplary and perfect" as mentioned during the meeting. [see here](https://github.com/bioimage-io/spec-bioimage-io/blob/gh-pages/user_docs/model_descr_v0-5.md#documentation-union).
Just an example:
![Screenshot 2024-11-15 at 13 51 59](https://github.com/user-attachments/assets/cf6c5941-d618-414e-8712-ab673d701c54)

**Comment by melisande-c** [comment]
We do include quite a lot of info (see below), what else are we missing apart from validation? And in regards to validation, should it be  something like "calculate PSNR using a ground truth image"? The thing with Noise2Void is, someone is likely using it because they don't have ground truth, but we can write it anyway.

![Screenshot 2024-11-15 at 15 05 04](https://github.com/user-attachments/assets/530bba28-93f0-4ed9-8f71-ecae01d71948)
![Screenshot 2024-11-15 at 15 05 21](https://github.com/user-attachments/assets/45b8ffe0-8ada-448f-bcdc-8b15c5b1679f)

**Comment by mese79** [comment]
> The documentation should include a '#[#] Validation' (sub)section with details on how to quantitatively validate the model on unseen data.

So, I guess the bioimage core testing, will throw a warning if it couldn't find a **#validation** section in the model's documents. However, the documentation about this optional spec is not very clear (and it was mentioned in the meeting).

**Comment by melisande-c** [comment]
Yeah I saw that quote on the link you provided in the first comment, so for us would it be something like "To validate the model on a dataset, calculate the PSNR using a ground truth image" (+ maybe some elaboration on PSNR and some other details.)? (That is if GT is available).

**Comment by mese79** [comment]
I remembered that they also asked to remove the top paragraph saying "This model is the output of an example notebook..."

**Comment by mese79** [comment]
> Yeah I saw that quote on the link you provided in the first comment, so for us would it be something like "To validate the model on a dataset, calculate the PSNR using a ground truth image" (+ maybe some elaboration on PSNR and some other details.)? (That is if GT is available).

Honestly, I'm not sure but seems like it. Also, many of the models in the bmz don't have a good/complete documents.

**Comment by melisande-c** [comment]
> I remembered that they also asked to remove the top paragraph saying "This model is the output of an example notebook..."

So all the CAREamics models we uploaded are created using notebooks that are available as example on the CAREamics website. The Hagen one is available [here](https://careamics.github.io/0.1/applications/Noise2Void/Hagen/). Unfortunately the link in the description is now broken, and apparently markdown formatting doesn't happen in that part of the description. I will update it when I get a chance.

EDIT:
So why should this paragraph removed? The formatting and link should definitely be fixed, maybe the wording, but surely providing a link to the notebook that was used to train the model is beneficial? It just happens to be a notebook that is used as an example of Noise2Void applications on the CAREamics website.

**Comment by jdeschamps** [comment]
Thanks a lot @mese79  for the feedback!

I also disagree with removing the notebook link, this is valuable info for users.

Regarding validation, we could write up a validation paragraph for each type of algorithm and pull it automatically in the README.

Actually there is a section in that regard on the website for Noise2Void (https://careamics.github.io/0.1/algorithms/Noise2Void/#assessing-quality-of-results), and we will need one for each algorithm. So we might as well two-birds-one-stone it.
