### ISSUE TITLE
Review and update BMZ export

### ISSUE THREAD

**Issue by melisande-c** [CAREamics/careamics#278]
List of TODOs for exporting to BMZ. Once these are completed we can create a new CAREamics release re-run our notebooks and re-upload the new versions of the models.

- [x] Review README creation
  - [x] Review information order, e.g. should data description come before algorithm configuration?
  - [x] Add validation description, as discussed in #276 
  - [x] Update links to docs (they are broken, `/latest` doesn't exist)
- [x] We need to add the covers, it seems there is no automatic cover generation, issue also open here #176 
- [x] We should relax the test kwargs, absolute and relative tolerance, this can be done by adding them to the rdf `config.bioimageio.test_kwargs`. This is where they are extracted during the CI tests: https://github.com/bioimage-io/collection/blob/efb7f06797574544385222de62b08f13ae99854d/bioimageio_collection_backoffice/run_dynamic_tests.py#L109-L115.

**Comment by melisande-c** [comment]
Additional point not to forget:

- [x] Formatting error: "algorithm description" should be a markdown heading, the same as for example the data description.

**Comment by mese79** [comment]
Just to share my experience, even though I've put a `### Validation` part into my model's `doc.md` file, still I've got the warning `No '# Validation' (sub)section found in doc.md.` .  
I haven't try to change the `### Validation` to `# Validation`, but the check shouldn't be such meticulous and limited to only the `h1` header.

**Comment by melisande-c** [comment]
In the documentation you shared in #276 it says

> '#[#] Validation' (sub)section with details on how to quantitatively validate the model on unseen data.

I assume this means it can be `h1` or `h2`

**Comment by jdeschamps** [comment]
So half meticulous. :)

**Comment by melisande-c** [comment]
Something we should also think about is the model versioning, it seems we hardcode the model version to be 0.1.0, but if a model needs to be updated I am not sure how the bmz handles this (I think different model versions are saved in different folders in the s3 bucket, but if the version is the same maybe it gets overwritten).

Below is where we hardcode the version:
https://github.com/CAREamics/careamics/blob/cc4cc04368e5286591266f9df2489546b656e826/src/careamics/model_io/bioimage/model_description.py#L294

**Comment by mese79** [comment]
This is the issue Caterina asked community partners to add some documentation:
https://github.com/bioimage-io/bioimage.io/issues/437
