### ISSUE TITLE
[BUG] Bioimage.io downloads site.config.json upon simply loading a configuration

### ISSUE THREAD

**Issue by jdeschamps** [CAREamics/careamics#82]
Bioimage.io downloads site.config.json upon simply loading a configuration, should not be the case.

**Comment by mese79** [comment]
As soon as you import bioimage.io or spec, you get this cache warning (if I understand what you mean correctly).  
But there is an environment variable `"BIOIMAGEIO_CACHE_WARNINGS_LIMIT"` with `3` as default value. I set it to zero in our `bioimage/__init__.py`, that should fix the issue.
